routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();
Route::get('/', 'PageController@index');

// Dim
Route::resource('dim', 'AssetsController');
// asset
Route::get('dimdata', 'AssetsController@getdata')->name('dim.data');
Route::get('removeasset', 'AssetsController@removeasset')->name('remove.asset');
Route::get('fetchasset', 'AssetsController@fetchasset')->name('fetch.asset');
// Measure Type
Route::get('measuretypedata', 'AssetsController@measuretypedata')->name('measuretype.data');
// Route::post('storemeasuretype', 'AssetsController@storemeasuretype')->name('store.measuretype');
Route::get('removemeasuretype', 'AssetsController@removemeasuretype')->name('remove.measuretype');
Route::get('fetchmeasuretype', 'AssetsController@fetchmeasuretype')->name('fetch.measuretype');

// Measure Status
Route::get('measurestatusdata', 'AssetsController@measurestatus')->name('measurestatus.data');
Route::post('storemeasurestatus', 'AssetsController@storemeasurestatus')->name('store.measurestatus');
Route::get('removemeasurestatus', 'AssetsController@removemeasurestatus')->name('remove.measurestatus');
Route::get('fetchmeasurestatus', 'AssetsController@fetchmeasurestatus')->name('fetch.measurestatus');

// client
Route::resource('clients', 'ClientController');
Route::get('datatable', 'ClientController@getdata')->name('clients.data');

// measures
Route::resource('measures', 'MeasureController');
Route::get('getdata', 'MeasureController@getdata')->name('measures.data');
Route::put('world', 'MeasureController@world')->name('measures.world');
Route::get('removedata', 'MeasureController@removedata')->name('measures.removedata');

//Managers
Route::resource('managers', 'ManagerController');
Route::get('managerdata', 'ManagerController@managerdata')->name('managers.data');
Route::get('removemanager', 'ManagerController@removedata')->name('manager.removedata');

app/Manager.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manager extends Model
{
    protected $table = 'manager_managers';
}

app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Manager;
use DataTables;
use Redirect;
use Alert;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('manager.index');
    }

    function managerdata()
    {
        $managers = Manager::all();
        return Datatables::of($managers)
        ->AddColumn('action', function($managers){
            return '<a href="managers/' . $managers->id . '/edit" class= "edit"><button class="wave-effect btn btn-success btn-bordred wave-light"><i class="fa fa-edit"></i></button></a>
                    <a href="#" id="'. $managers->id .'" class="delete"><button class="wave-effect btn btn-danger btn-bordred wave-light delete"><i class="fa fa-times"></i></button></a>';
        })
        ->make(true);
    }

    function removedata(Request $request)
    {
        $manager = Manager::find($request->input('id'));
        $manager->delete();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manager.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'managername' => 'required'
        ]);

        $manager = new Manager;
        $manager->manager_name = $request->input('managername');
        $manager->manager_status_id = $request->input('managerstatus');
        $manager->manager_product_id = $request->input('managerproduct');
        $manager->manager_industry_id = $request->input('managerindustry');
        $manager->qualification_id = $request->input('qualification');
        $manager->company_info = $request->input('companyinfo');
        $manager->manager_evaluation = $request->input('managerevaluation');
        $manager->address = $request->input('address');
        $manager->city = $request->input('city');
        $manager->province_id = $request->input('state');
        $manager->country_id = $request->input('country');
        $manager->phone = $request->input('phone');
        $manager->other_office = $request->input('otheroffice');
        $manager->year_founded = $request->input('yearfounded');
        $manager->discountinue_date = $request->input('discontinuedate');
        $manager->engagement_minimum = $request->input('engagementminimum');
        $manager->engagement_notes = $request->input('engagementnotes');
        $manager->institutional_minimum = $request->input('institutionalminimum');
        $manager->institutional_fees = $request->input('institutionalfee');
        $manager->private_client_minimum = $request->input('privateclientminimum');
        $manager->private_client_fees = $request->input('privateclientfee');
        $manager->aboriginal_minimum = $request->input('aboriginalminimum');
        $manager->aboriginal_fees = $request->input('aborignalfee');
        $manager->aboriginal_notes = $request->input('aboriginalnotes');
        $manager->npf_minimum = $request->input('npfminimum');
        $manager->npf_fees = $request->input('npffee');
        $manager->affiliations = $request->input('affiliation');
        $manager->notes = $request->input('notes');
        if ($manager->save()){
            Alert::success('Saved!');
        };

        return Redirect('/managers');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manager = Manager::find($id);
        return view('manager.edit')->with('manager', $manager);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'managername' => 'required'
        ]);

        
        $manager = Manager::find($id);
        $manager->manager_name = $request->input('managername');
        
        if($manager->save()){
            Alert::success('Updated!');
        }

        return Redirect('/managers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/manager/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <button id="goback" class="btn btn-success pull-right goback">Go Back</button>

        <h1 class="page-header">New Manager</h1>

<legend class="no-border f-w-700 p-b-0 m-t-0 m-b-20 f-s-16 text-inverse">Manager Details</legend>

<form action="{{ route('managers.store') }}" method="POST" class="margin-bottom-0">
    @csrf
    {{-- Manager Name --}}
    <label class="p-2 text-md-right col-form-label">Manager Name<span class="text-danger">*</span></label>
    <div class="col-md-10"> 
        <input id="managername" type="text" class="form-control{{ $errors->has('managername') }}" name="managername" required autofocus>

        @if ($errors->has('managername'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('managername') }}</strong>
            </span>
        @endif
    </div>

    {{-- Manager Status --}}
    <label class="p-2 text-md-right col-form-label">Manager Status</label>
    <div class="col-md-10"> 
        <select id="managerstatus" class="form-control" name="managerstatus">
            <option value="">--Measure Status--</option>
            {{-- @foreach($assets as $asset)
            <option value="{{ $asset->asset_class }}">{{ $asset->asset_class }}</option>
            @endforeach --}}
        </select>
    </div>

    {{-- Manager Product --}}
    <label class="p-2 text-md-right col-form-label">Manager Product</label>
    <div class="col-md-10"> 
        <select id="managerproduct" class="form-control" name="managerproduct">
            <option value="">--Manager Product--</option>
            {{-- @foreach($assets as $asset)
            <option value="{{ $asset->asset_class }}">{{ $asset->asset_class }}</option>
            @endforeach --}}
        </select>
    </div>
    {{-- Manager Industry --}}
    <label class="p-2 text-md-right col-form-label">Manager Industry</label>
    <div class="col-md-10"> 
        <select id="managerindustry" class="form-control" name="managerindustry">
            <option value="">--Manager Industry--</option>
            {{-- @foreach($assets as $asset)
            <option value="{{ $asset->asset_class }}">{{ $asset->asset_class }}</option>
            @endforeach --}}
        </select>
    </div>

    {{-- Qualification --}}
    <label class="p-2 text-md-right col-form-label">Qualification</label>
    <div class="col-md-10"> 
        <select id="qualification" class="form-control" name="qualification">
            <option value="">--Qualification--</option>
            {{-- @foreach($assets as $asset)
            <option value="{{ $asset->asset_class }}">{{ $asset->asset_class }}</option>
            @endforeach --}}
        </select>
    </div>

    {{-- Company Info --}}
    <label class="p-2 text-md-right col-form-label">Company Info</label>
    <div class="col-md-10"> 
        <textarea id="companyinfo" class="form-control" name="companyinfo"></textarea>
    </div>

    {{-- Managers Info --}}
    <label class="p-2 text-md-right col-form-label">Manager's Evaluation</label>
    <div class="col-md-10"> 
        <textarea id="managerevaluation" class="form-control" name="managerevaluation"></textarea>
    </div>

    {{-- Address --}}
    <label class="p-2 text-md-right col-form-label">Street Address</label>
    <div class="col-md-10"> 
        <input id="address" class="form-control" name="address" />
    </div>
    {{-- City and Postal Code --}}
   <div class="form-group m-t-15">
        <div class="col-md-10">
            <div class="row row-space-6">
                <div class="col-6"> 
                    <label class="p-2 text-md-right col-form-label">City</label>
                    <input id="city" class="form-control" name="city" />
                </div>
                <div class="col-3">
                    <label class="p-2 text-md-right col-form-label">Postal Code</label>
                    <input id="postalcode" class="form-control" name="postalcode" />
                </div>
            </div>
        </div>
    </div>
{{-- State and Contry --}}
<div class="form-group m-t-15">
    <div class="col-md-10">
        <div class="row row-space-6">
            <div class="col-6"> 
                <label class="p-2 text-md-right col-form-label">State</label>
                <select id="state" class="form-control" name="state">
                    <option value="">--State--</option>
                </select>
            </div>
            <div class="col-6">
                <label class="p-2 text-md-right col-form-label">Country</label>
                <select id="country" class="form-control" name="country">
                    <option value="">--Country--</option>
                </select>
            </div>
        </div>
    </div>
</div>

{{-- Phone --}}
<label class="p-2 text-md-right col-form-label">Phone Number</label>
<div class="col-md-5"> 
    <input id="phone" class="form-control" name="phone" />
</div>

{{-- Other Office --}}
<label class="p-2 text-md-right col-form-label">Other Office</label>
<div class="col-md-10"> 
    <input id="otheroffice" class="form-control" name="otheroffice" />
</div>

{{-- Year Founded --}}
<label class="p-2 text-md-right col-form-label">Year Founded</label>
<div class="col-md-5"> 
    <input id="yearfounded" class="form-control" name="yearfounded" />
</div>

{{-- Discountinue Date --}}
<label class="p-2 text-md-right col-form-label">Discountinue Date</label>
<div class="col-md-5"> 
    <input id="discontinuedate" class="form-control" name="discontinuedate" />
</div>

<div class="form-group m-t-15">
    <div class="col-md-10">
        <div class="row row-space-6">
            <div class="col-6">
                {{-- Engagement --}}
                <div id="accordion" class="card-accordion">
                    <!-- begin card -->
                    <div class="card">
                        <div class="card-header bg-blue text-white pointer-cursor" data-toggle="collapse" data-target="#collapseOne">
                            <i class="fas fa-lg fa-fw m-r-10 fa-link"></i>Engagement
                        </div>
                        <div id="collapseOne" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                <label>Minimum</label> 
                                    <input id="engagementminimum" class="form-control" name="engagementminimum" />
                                <label class="p-2 text-md-right col-form-label">Notes</label>
                                    <textarea id="engagementnotes" class="form-control" name="engagementnotes"></textarea>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
            {{-- Institutional --}}
            <div class="col-6">
                <div id="institutional" class="card-accordion">
                    <!-- begin card -->
                    <div class="card">
                        <div class="card-header bg-blue text-white pointer-cursor" data-toggle="collapse" data-target="#collapseInstitutional">
                            <i class="fas fa-lg fa-fw m-r-10 fa-users"></i>Institutional
                        </div>
                        <div id="collapseInstitutional" class="collapse" data-parent="#institutional">
                            <div class="card-body">
                                <label>Minimum</label> 
                                    <input id="institutionalminimum" class="form-control" name="institutionalminimum" />
                                <label class="p-2 text-md-right col-form-label">Fee</label>
                                    <textarea id="institutionalfee" class="form-control" name="institutionalfee"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="form-group m-t-15">
        <div class="col-md-10">
            <div class="row row-space-6">
            <div class="col-6">
            {{-- Private Client --}}
            <div id="privateclient" class="card-accordion">
                    <!-- begin card -->
                    <div class="card">
                        <div class="card-header bg-blue text-white pointer-cursor" data-toggle="collapse" data-target="#collapsePrivateclient">
                            <i class="fas fa-lg fa-fw m-r-10 fa-lock"></i>Private Client
                        </div>
                        <div id="collapsePrivateclient" class="collapse" data-parent="#privateclient">
                            <div class="card-body">
                                <label>Minimum</label> 
                                    <input id="privateclientminimum" class="form-control" name="privateclientminimum" />
                                <label class="p-2 text-md-right col-form-label">Fee</label>
                                    <textarea id="privateclientfee" class="form-control" name="privateclientfee"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                {{-- Aborignal --}}
                <div id="aboriginal" class="card-accordion">
                        <!-- begin card -->
                        <div class="card">
                            <div class="card-header bg-blue text-white pointer-cursor" data-toggle="collapse" data-target="#collapseAboriginal">
                                <i class="fas fa-lg fa-fw m-r-10 fa-industry"></i>Aboriginal
                            </div>
                            <div id="collapseAboriginal" class="collapse" data-parent="#aboriginal">
                                <div class="card-body">
                                    <label>Minimum</label> 
                                        <input id="aboriginalminimum" class="form-control" name="aboriginalminimum" />
                                    <label>Fee</label>
                                        <textarea id="aborignalfee" class="form-control" name="aborignalfee"></textarea>
                                    <label>Notes</label>
                                        <textarea id="aboriginalnotes" class="form-control" name="aboriginalnotes"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="form-group m-t-15">
    <div class="col-md-10">
        <div class="row row-space-6">
            <div class="col-6">
            {{-- NPF --}}
            <div id="npf" class="card-accordion">
                    <!-- begin card -->
                    <div class="card">
                        <div class="card-header bg-blue text-white pointer-cursor" data-toggle="collapse" data-target="#collapsenpf">
                            <i class="fas fa-lg fa-fw m-r-10 fa-wrench"></i>NPF
                        </div>
                        <div id="collapsenpf" class="collapse" data-parent="#npf">
                            <div class="card-body">
                                <label>Minimum</label> 
                                    <input id="npfminimum" class="form-control" name="npfminimum" />
                                <label class="p-2 text-md-right col-form-label">Fee</label>
                                    <textarea id="npffee" class="form-control" name="npffee"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- Affiliation --}}
<label class="p-2 text-md-right col-form-label">Affiliation</label>
<div class="col-md-10"> 
    <input id="affiliation" class="form-control" name="affiliation" />
</div>

{{-- Notes --}}
<label class="p-2 text-md-right col-form-label">Notes</label>
<div class="col-md-10"> 
    <input id="notes" class="form-control" name="notes" />
</div>

    <div class="m-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    $('.goback').click(function (){
    swal({
        title: "You have unsaved changes.",
        text: "Are you sure to leave this page and discard your changes?",
        icon: "warning",
        buttons: true,
        })
        .then((goback) => {
        if (goback) {
            window.location.href = "/managers"
        }
        });
    });
});
</script>
@endpush
@endsection

resources/views/manager/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <button id="goback" class="btn btn-success pull-right goback">Go Back</button>

        <h1 class="page-header">New Manager</h1>

<legend class="no-border f-w-700 p-b-0 m-t-0 m-b-20 f-s-16 text-inverse">Manager Details</legend>
<form action="{{route('managers.update', $manager->id )}}" method="POST" class="margin-bottom-0">
    @csrf
    {{-- Measure Name --}}
    <label class="p-2 text-md-right col-form-label">Manager Name<span class="text-danger">*</span></label>
    <div class="col-md-10"> 
        <input value="{{$manager->manager_name}}" type="text" class="form-control{{ $errors->has('managername') }}" name="managername" required autofocus>

        @if ($errors->has('managername'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('managername') }}</strong>
            </span>
        @endif
    </div>

    <div class="m-3">
        {{ method_field('PUT') }}
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    $('.goback').click(function (){
    swal({
        title: "You have unsaved changes.",
        text: "Are you sure to leave this page and discard your changes?",
        icon: "warning",
        buttons: true,
        })
        .then((goback) => {
        if (goback) {
            window.location.href = "/managers"
        }
        });
    });
});
</script>
@endpush
@endsection

resources/views/manager/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="m-10"><a href="{{ route('managers.create')}}" class="btn btn-info pull-right">New</a></div>
    <h1 class="page-header">Manager</h1>
    <div class="table-responsive">
    <table id="manager_table" class="table table-striped m-b-0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th width="15%">Action</th>
                </tr>
            </thead>
        </table> 
    </div>
</div>

@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('#manager_table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": "{{ route('managers.data') }}",
            "columns":[
                { "data": "id" },
                { "data": "manager_name" },
                { "data": "action", orderable:false, searchable: false}
            ]
        });

       $(document).on('click', '.delete', function(){
            var id = $(this).attr('id');
        swal({
            title: "Are you sure",
            text: "This record will be deleted permanently.",
            icon: "warning",
            buttons: true,
            dangerMode: true
            })
            .then((removedata) => {
            if (removedata) {
                $.ajax({
                url:"{{route('manager.removedata')}}",
                method:"get",
                data:{id:id},
                success:function(data)
                {
                    swal("Deleted!", "", "success");
                    $('#manager_table').DataTable().ajax.reload();
                }
            })
            }
            else
            {
                return false;
            }
        });
    });
});
</script>
@endpush
@endsection