routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();
Route::get('/', 'PageController@index');

// Dim
Route::resource('dim', 'AssetsController');
// asset
Route::get('dimdata', 'AssetsController@getdata')->name('dim.data');
Route::get('removeasset', 'AssetsController@removeasset')->name('remove.asset');
Route::get('fetchasset', 'AssetsController@fetchasset')->name('fetch.asset');
// Measure Type
Route::get('measuretypedata', 'AssetsController@measuretypedata')->name('measuretype.data');
// Route::post('storemeasuretype', 'AssetsController@storemeasuretype')->name('store.measuretype');
Route::get('removemeasuretype', 'AssetsController@removemeasuretype')->name('remove.measuretype');
Route::get('fetchmeasuretype', 'AssetsController@fetchmeasuretype')->name('fetch.measuretype');

// Measure Status
Route::get('measurestatusdata', 'AssetsController@measurestatus')->name('measurestatus.data');
Route::post('storemeasurestatus', 'AssetsController@storemeasurestatus')->name('store.measurestatus');
Route::get('removemeasurestatus', 'AssetsController@removemeasurestatus')->name('remove.measurestatus');
Route::get('fetchmeasurestatus', 'AssetsController@fetchmeasurestatus')->name('fetch.measurestatus');

// client
Route::resource('clients', 'ClientController');
Route::get('datatable', 'ClientController@getdata')->name('clients.data');

// measures
Route::resource('measures', 'MeasureController');
Route::get('getdata', 'MeasureController@getdata')->name('measures.data');
Route::put('world', 'MeasureController@world')->name('measures.world');
Route::get('removedata', 'MeasureController@removedata')->name('measures.removedata');

//Managers
Route::resource('managers', 'ManagerController');
Route::get('managerdata', 'ManagerController@managerdata')->name('managers.data');
Route::get('removemanager', 'ManagerController@removedata')->name('manager.removedata');

resources/views/include/message.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('success'))
        <div class="alert alert-success">
            {{session('success')}}
        </div>
@endif

@if(session('error'))
        <div class="alert alert-danger">
            {{session('error')}}
        </div>
@endif

resources/views/include/navbar.blade.php
<!-- begin #header -->
<div id="header" class="header navbar-default">
        <!-- begin navbar-header -->
        <div class="navbar-header">
            <a href="index.html" class="navbar-brand"><span class="navbar-logo"></span> <b>KPW</b> Admin</a>
            <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- end navbar-header -->
        
        <!-- begin header-nav -->
        <ul class="navbar-nav navbar-right">
            <li class="dropdown navbar-user">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="img/user/user-13.jpg" alt="" /> 
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span> <b class="caret"></b>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        <!-- end header navigation right -->
    </div>
    <!-- end #header -->

resources/views/include/sidebar.blade.php
<div id="page-container" class="page-container fade page-sidebar-fixed page-header-fixed">
<!-- begin #sidebar -->
<div id="sidebar" class="sidebar">
        <!-- begin sidebar scrollbar -->
        <div data-scrollbar="true" data-height="100%">
            <!-- begin sidebar user -->
            <ul class="nav">
                <li class="nav-profile">
                    <a href="javascript:;" data-toggle="nav-profile">
                        <div class="cover with-shadow"></div>
                        <div class="image">
                            <img src="img/user/user-13.jpg" alt="" />
                        </div>
                        <div class="info">
                            <b class="caret pull-right"></b>
                            {{ Auth::user()->name }}
                        </div>
                    </a>
                </li>
                <li>
                    <ul class="nav nav-profile">
                        <li><a href="javascript:;"><i class="fa fa-cog"></i> Settings</a></li>
                    </ul>
                </li>
            </ul>
            <!-- end sidebar user -->
            <!-- begin sidebar nav -->
            <ul class="nav">
                <li class="nav-header">Navigation</li>

                <li>
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-users"></i>
                        <span>Client</span>
                    </a>
                    {{-- <ul class="sub-menu">
                        <li class="active"><a href="#">Clients</a></li>
                        <li><a href="#">Client's Account</a></li>
                        <li><a href="#">Client's Report</a></li>
                    </ul> --}}
                </li>

                <li>
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-folder-open"></i> 
                        <span>Accounts</span>
                    </a>
                </li>

                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-industry"></i> 
                        <span>Managers</span>
                    </a>
                    <ul class="sub-menu">
                        <li class="active"><a href="{{ route('managers.index') }}">List<i class="fa fa-paper-plane text-theme m-l-5"></i></a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-cubes"></i> 
                        <span>Products</span>
                    </a>
                </li>

                <li class="has-sub">
                    <a href="#">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-flask"></i> 
                        <span>Measures</span> 
                    </a>
                    <ul class="sub-menu">
                        <li class="active"><a href="{{ route('measures.index') }}">List<i class="fa fa-paper-plane text-theme m-l-5"></i></a></li>
                        <li><a href="{{ route('dim.index') }}">Dim</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-unlock-alt"></i> 
                        <span>Securities</span> 
                    </a>
                </li>

                <li>
                    <a href="#">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-address-book"></i> 
                        <span>Contacts</span> 
                    </a>
                </li>

                <li>
                    <a href="#">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-cart-plus"></i> 
                        <span>Items</span> 
                    </a>
                </li>

                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fas fa-lg fa-fw m-r-10 fa-chart-line"></i>
                        <span>Reports</span> 
                    </a>
                    <ul class="sub-menu">
                        <li><a href="javascript:;"><i class="fa fa-paper-plane text-theme m-l-5"></i> General</a></li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fa fa-key"></i>
                        <span>Administration</span>
                    </a>

                    <ul class="sub-menu">
                        <li><a href="#">Login</a></li>
                    </ul>
                </li>
                <!-- begin sidebar minify button -->
				<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
				<!-- end sidebar minify button -->
            </ul>
        </div>      
    </div>